### ISSUE TITLE
What does the "Join Shared Session" command do?

### ISSUE THREAD

**Issue by JoelAnderson-UU** [peerdraft/obsidian-plugin#2]
What does the "Join Shared Session" command do?  It doesn't seem to have any effect.  But would very nice to be able to restart a note that was closed, in such a way that collaborators could continue using the same code, rather than having to send them a new code. 

Ideally, I'd like to store the relevant share-code URL in a note's Properties (`peerdrafid:`), and then perhaps click on it to resume sharing.

The main thing though is to be able to reuse the share codes.

**Comment by schlundd** [comment]
The command should open a popup asking for a peerdraft URL. This is the URL someone else would give you to join their session.

![Selection_309](https://github.com/peerdraft/obsidian-plugin/assets/1160643/8f75c968-5ec2-4fdc-9ccc-f06ccd705947)

Does it not open the dialog for you?

Regarding the re-use of codes, I'll open a new Feature Request.

**Comment by JoelAnderson-UU** [comment]
I think I've figured out what's going on:  It wasn't clear from your reply _**or from any of the documentation**_ (or the various YouTube videos explaining this), but it seems that it is now possible for guest-collaborators to establish a peer-to-peer connection, from **inside their own instance of Obsidian**. Wow! 

**As I understand it now**:  it is now possible to join a peer-to-peer session from within another Obsidian vault.  Once the host-collaborator shares the URL with the guest-collaborators, the guest-collaborators can open an Obsidian vault on their own computer (as long as the Peerdraft plugin is installed), run the "Join shared session" command, and then paste the URL at the prompt.  

What is confusing, however, is that there is no warning about the fact that, if you switch to another note, and try to switch back to the collaboration, the session will have ended.  Perhaps there needs to be a pop-up that asks, "Do you want to close this session? Closing this note with end the peer-to-peer connection with Peerdraft."

In any case, it's probably a good idea to warn collaborators to use the "Pin" command to make sure that the collaborative session stays open.

**Comment by schlundd** [comment]
Thanks for the hint about the pin command. Notes get auto-pinned on starting/joining a session now (#4).
