### ISSUE TITLE
User input hides text

### ISSUE THREAD

**Issue by devinat1** [peerdraft/obsidian-plugin#5]
It would be great if the user collaborator bar was a bit more subtle, since it hides the text it surrounds:
![image](https://github.com/peerdraft/obsidian-plugin/assets/15788108/e20502ef-e817-40e6-a43f-e2dde0d2e479)

**Comment by schlundd** [comment]
Hiding the name completely seems "too subtle". How about I'll make it semi-transparent unless you hover over it. I'll also make it a bit smaller on the web version.
