### ISSUE TITLE
2.4.0 requires 2.3.X to configure initially

### ISSUE THREAD

**Issue by dragos240** [peerdraft/obsidian-plugin#8]
I installed 2.4.0 originally from the community plugins section and found upon enabling, I didn't see anything. I tried to use a command, but none appeared. I opened the inspector window and saw that it tried to load settings but it came back null. I tried uninstalling and manually installing 2.4.0, but saw the same behavior. Then I tried 2.3.2 and it allowed me to configure the plugin, after which I was able to update to 2.4.0

**Comment by schlundd** [comment]
Thank you for the report and the tests!

**Comment by schlundd** [comment]
Fixed in 2.4.1
