### ISSUE TITLE
Latest version does not work on mobile, even if configured on 2.3.X

### ISSUE THREAD

**Issue by dragos240** [peerdraft/obsidian-plugin#9]
The plugin works completely on 2.3.2 but once 2.4.1 is installed, it breaks and neither commands nor settings work.

Platform: Android 14
Phone: Asus Zenfone 10

**Comment by schlundd** [comment]
Sorry. Not sure how that happend. Fix is on the way.

**Comment by schlundd** [comment]
Fixed in 2.4.2
